apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-bff
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - image: public.ecr.aws/v1o5d7a8/kafka-app/bff:latest
          name: kafka-bff
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
