apiVersion: v1
kind: Pod
metadata:
  name: kafka-bff
spec:
  containers:
    - image: public.ecr.aws/v1o5d7a8/kafka-app/bff:latest
      name: kafka-bff
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
