apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-user
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-user
  template:
    metadata:
      labels:
        app: kafka-user
    spec:
      containers:
        - image: public.ecr.aws/v1o5d7a8/kafka-app/user:latest
          name: kafka-user
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
